remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  skin: auto
  hide_site_feed_link: true

title: Gunhui’s Blog

author:
  email: gunhui@kakao.com

description: >
  배운 것들을 기록하고자 합니다.
  GNU/Linux, Apple Mac, 임베디드 시스템에 관심이 있습니다.