remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  skin: auto

title: Gunhui’s Blog

author:
  email: gunhui@kakao.com

social_links:
  - icon: github
    url: https://github.com/gunhui01